spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      authentication-database: admin
      username: root
      password: 'example'
      uri: mongodb://root:example@127.0.0.1:27017/
      database: admin